# Generated by Django 5.1.4 on 2025-06-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docvault", "0003_documentcategory_alter_document_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="docvault.documentcategory",
            ),
            preserve_default=False,
        ),
    ]
