# Generated by Django 5.1.4 on 2025-06-24 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docvault", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentaccess",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="documentaccess",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentaccess",
            name="granted_by",
        ),
        migrations.RemoveField(
            model_name="documentaccess",
            name="user",
        ),
        migrations.RemoveField(
            model_name="document",
            name="category",
        ),
        migrations.RemoveField(
            model_name="document",
            name="tags",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="last_modified_at",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="current_version",
        ),
        migrations.RemoveField(
            model_name="document",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="document",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="document",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="document",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="document",
            name="status",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="change_summary",
        ),
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(
                default="", help_text="The main content of the document"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="URL-friendly version of the title",
                max_length=200,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="content",
            field=models.TextField(help_text="The content for this version"),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Changelog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of changes made"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelogs",
                        to="docvault.document",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changelog",
                        to="docvault.documentversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ChangeRecord",
        ),
        migrations.DeleteModel(
            name="DocumentAccess",
        ),
        migrations.DeleteModel(
            name="DocumentCategory",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
