# Generated by Django 5.1.4 on 2025-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docvault", "0004_alter_document_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="changelog",
            name="importance",
            field=models.CharField(
                choices=[
                    ("MINOR", "Minor - Small wording or formatting changes"),
                    ("NORMAL", "Normal - Notable changes to content"),
                    ("MAJOR", "Major - Critical changes that users should be aware of"),
                ],
                default="NORMAL",
                help_text="Determines visibility in the global changelog",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="changelog",
            name="show_in_global",
            field=models.BooleanField(
                default=False,
                help_text="Explicitly include this change in the global changelog regardless of importance",
            ),
        ),
    ]
