# Generated by Django 5.2.3 on 2025-07-18 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docvault", "0005_changelog_importance_changelog_show_in_global"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(help_text="The main content of the document"),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date/time the document was created",
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="content",
            field=models.TextField(help_text="The content for this version"),
        ),
    ]
