# Generated by Django 5.2.3 on 2025-07-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docvault", "0006_alter_document_content_alter_document_created_at_and_more"),
        ("docvault", "0006_materialized_path_refactor"),
    ]

    operations = []
