# Generated by Django 5.2.3 on 2025-07-19 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docvault", "0007_merge_20250719_0058"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentcategory",
            new_name="docvault_do_path_5fd166_idx",
            old_name="docvault_doc_path_idx",
        ),
        migrations.RenameIndex(
            model_name="documentcategory",
            new_name="docvault_do_depth_47236a_idx",
            old_name="docvault_doc_depth_idx",
        ),
        migrations.RenameIndex(
            model_name="documentcategory",
            new_name="docvault_do_path_cb5b1b_idx",
            old_name="docvault_doc_path_depth_idx",
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly identifier for the category", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["slug"], name="docvault_do_slug_f6c98c_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category", "slug"], name="docvault_do_categor_0f7a87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category_id"], name="docvault_do_categor_63b24d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["updated_at"], name="docvault_do_updated_856fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="docvault_do_created_1cfc70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(fields=["slug"], name="docvault_do_slug_c6fa3b_idx"),
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(
                fields=["parent", "slug"], name="docvault_do_parent__24382f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(
                fields=["parent_id"], name="docvault_do_parent__d043ac_idx"
            ),
        ),
    ]
